apiVersion: '2018-10-01'
location: eastus
name: aci_video-rental-service
properties:
  containers:
  - name: video-rental-service
    properties:
      image: matnos/uni-movie_rental_service
      requests:
        memory: "100M"
        cpu: "250m"
      limits:
        memory: "200M"
        cpu: "5000m"
      ports:
      - port: 8000
  osType: Linux
  restartPolicy: Always
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 8000
