apiVersion: '2018-10-01'
location: eastus
name: aci-movie-rental-service
properties:
  containers:
  - name: movie-rental-service
    properties:
      image: matnos/uni-movie_rental_service
      requests:
        memory: "100M"
        cpu: "250m"
      limits:
        memory: "200M"
        cpu: "5000m"
      ports:
      - port: 8000
  osType: Linux
  restartPolicy: OnFailure
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 8000
