apiVersion: '2018-10-01'
location: eastus
name: aci_video-rental-service
properties:
  containers:
  - name: video-rental-service
    properties:
      image: wypozyczalniaWideo.azurecr.io/video-rental-service:latest
      resources:
        requests:
          cpu: 0.5
          memoryInGB: 0.5
      ports:
      - port: 8000
  osType: Linux
  restartPolicy: Always
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 8000
