apiVersion: '2018-10-01'
location: eastus
name: aci_video-rental-database
properties:
  containers:
  - name: video-rental-database
    properties:
      image: wypozyczalniaWideo.azurecr.io/video-rental-database:latest
      ports:
      - port: 27017
  osType: Linux
  restartPolicy: Always
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 27017
