apiVersion: '2018-10-01'
location: eastus
name: aci_video-rental-database
properties:
  containers:
  - name: video-rental-database
    properties:
      image:wypozyczalniawideo.azurecr.io/video-rental-database:latest
      resources:
        requests:
          cpu: 0.5
          memoryInGB: 0.5
      ports:
      - port: 27017
  osType: Linux
  restartPolicy: Always
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 27017
