apiVersion: '2018-10-01'
location: eastus
name: aci_movie-rental-database
properties:
  containers:
  - name: movie-rental-database
    properties:
      image: matnos/uni-movie_rental_database
      resources:
        requests:
          cpu: 0.5
          memoryInGB: 0.5
      ports:
      - port: 27017
  osType: Linux
  restartPolicy: OnFailure
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 27017
