version: '3'
services:
  movie-rental-service:
    image: matnos/uni-movie_rental_service:latest
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: "mongodb://movie-rental-database:27017"
      PORT: 8000
      SSL_CERT: ${SSL_CERT}
      SSL_KEY: ${SSL_KEY}
    depends_on:
      - movie-rental-database

  movie-rental-database:
    image: matnos/uni-movie_rental_database:latest
    ports:
      - "27017:27017"
