name: Build and push Docker image to ACR, then deploy to ACI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build and Push Docker Images
        run: |
          docker build -t matnos/uni-movie_rental_service:latest .
          docker build -t matnos/uni-movie_rental_database:latest -f Dockerfile-db .

          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push matnos/uni-movie_rental_service:latest
          docker push matnos/uni-movie_rental_database:latest

      - name: Deploy to Azure Container Instances
        run: |
          docker-compose -f docker-compose.yml up

    env:
      MONGO_DB_URL: ${{ secrets.MONGODB_URI }}
      PORT: ${{ secrets.PORT }}
      SSL_CERT: ${{ secrets.SSL_CERT }}
      SSL_KEY: ${{ secrets.SSL_KEY }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
